# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Expose ports to the host.
  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1"    # Nomad
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"    # Nomad Autoscaler health check
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"    # Demo webapp

  # Share current directory with jobs and configuration files with the VM. Add
  # the shared files in a sub-dir.
  config.vm.synced_folder "./", "/home/vagrant/nomad"
  config.vm.synced_folder "../dist", "/home/vagrant/nomad-autoscaler-plugins"

  # VM configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ] # https://bugs.launchpad.net/cloud-images/+bug/1874453
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Provision demo dependencies.
  #   - Downloads and install Nomad and Docker
  # Only runs when the VM is created.
  config.vm.provision "deps", type: "shell", inline: <<-SHELL

    mkdir /tmp/downloads

    # Install dependencies.
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      jq \
      software-properties-common \
      zip

    nomad_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/nomad | jq -r '.current_version')

    # Download and install Docker.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
    apt-get update
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io
    docker run hello-world
    usermod -aG docker vagrant

    # Install Hey.
    apt-get install -y hey

    # Download and install Nomad and Consul.
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all \
      https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip
    unzip nomad_${nomad_version}_linux_amd64.zip
    # unzip consul_${consul_version}_linux_amd64.zip
    mkdir -p /opt/hashicorp/bin
    mv nomad consul /opt/hashicorp/bin
    chmod +x /opt/hashicorp/bin/nomad
    ln -s /opt/hashicorp/bin/nomad /usr/local/bin
    popd

    rm -fr /tmp/downloads
  SHELL

  # Setup demo dependencies.
  #   - Create daemons for Nomad
  # Runs everytime the VM starts.
  config.vm.provision "app:setup", type: "shell", run: "always", inline: <<-SHELL
    # Create paths for Nomad host volumes.

    # Configure the Nomad daemons.
    pushd /home/vagrant/nomad/files
    cp nomad.service /etc/systemd/system/
    mkdir -p /etc/nomad.d
    popd

    # Copy across the config files.
    cp /home/vagrant/nomad/files/nomad.hcl /etc/nomad.d/

    # Enable and start the daemons
    sudo systemctl enable nomad
    sudo systemctl start nomad

    sleep 10

    nomad job run /home/vagrant/nomad/jobs/webapp.nomad
    # nomad job run /home/vagrant/nomad/jobs/autoscaler.nomad
  SHELL

end
