name: CI

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, linux, x64, lob-runner]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: make test build