name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, lob-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Build
        run: make test dist

      - name: Publish (Public)
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"

      - name: Publish (Internal)
        run: |
          aws s3 sync dist s3://nomad-autoscaler-cloudwatch-apm/${{github.event.release.tag_name}} --acl private --delete
