name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, lob-runner]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - run: make test dist

      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"

      - run: |
          aws s3 sync dist s3://nomad-autoscaler-cloudwatch-apm.lob-ci.com/nomad-autoscaler-cloudwatch-apm/{{ github.event.release.tag_name }} --acl private --delete